require ("plugins")
require ("core.base")
require ("core.colorscheme")
require ("core.keymaps")

require ("plugins-setup.nvim-tree")
require ("plugins-setup.lualine")
require ("plugins-setup.bufferline")
require ("plugins-setup.nvim-cmp")
require ("plugins-setup.lsp.mason")
require ("plugins-setup.lsp.lspsaga")
require ("plugins-setup.lsp.lspconfig")
require ("plugins-setup.treesitter")
require ("plugins-setup.autopairs")
require ("plugins-setup.blankline")
require ("plugins-setup.floaterm")
require ("plugins-setup.bufremove")
